controller:
  state:
    type: "joint_state_controller/JointStateController"
    publish_rate: 10

  tracks:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ["left_track_front_wheel_joint", "left_track_back_wheel_joint"]
    right_wheel: ["right_track_front_wheel_joint", "right_track_back_wheel_joint"]
    publish_rate: 10
    pose_covariance_diagonal: [0.001, 0.001, 10000.0, 10000.0, 10000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 10000.0, 10000.0, 0.03]
    enable_odom_tf: false
    estimate_velocity_from_position: false # hardware gives wheel velocity only
    wheel_separation: 0.14
    cmd_vel_timeout: 0.15
    velocity_rolling_window_size: 2
    wheel_separation_multiplier: 1.5

    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 6.0 # rad/s
        has_acceleration_limits: true
        max_acceleration: 3.0
