# http://wiki.ros.org/costmap_2d/flat

local_costmap:
  global_frame: map                # Should it be odom???
  robot_base_frame: base_footprint
  update_frequency:  5.0           # (per second) How fast the costmap should be updated (how often new sensor data is integrated)
  publish_frequency: 2.0           # (per second) How often to update RVIZ display
  # Specifies the delay in transform (tf) data that is tolerable in seconds.
  # This parameter serves as a safeguard to losing a link in the tf tree while
  # still allowing an amount of latency the user is comfortable with to exist in the system.
  # For example, a transform being 0.2 seconds out-of-date may be tolerable,
  # but a transform being 8 seconds out of date is not.
  # If the tf transform between the coordinate frames specified by the global_frame and
  # robot_base_frame parameters is transform_tolerance seconds older than ros::Time::now(),
  # then the navigation stack will stop the robot.
  transform_tolerance: 1.0
  rolling_window: true
  width:  4              # The width of the map in meters.
  height: 4              # The height of the map in meters.
  resolution: 0.02       # The resolution of the map in meters/cell.

  plugins:
    - {name: obstacle_layer,  type: costmap_2d::ObstacleLayer}
    - {name: inflation_layer, type: costmap_2d::InflationLayer}

  obstacle_layer:
    enabled: true
    footprint_clearing_enabled: true
    observation_sources: scan
    scan: {sensor_frame: rplidar_laser_link, data_type: LaserScan, topic: diffbot/scan, marking: true, clearing: true}
  
  inflation_layer:
    enabled: true
    cost_scaling_factor: 2.58     # https://kaiyuzheng.me/documents/papers/ros_navguide.pdf
    inflation_radius: 1.75        # https://kaiyuzheng.me/documents/papers/ros_navguide.pdf