
# Move base params

base_local_planner: dwa_local_planner/DWAPlannerROS
base_global_planner: navfn/NavfnROS
shutdown_costmaps: false
controller_frequency: 5.0        # If too low movement is jerky
planner_patience: 5.0
controller_patience: 15.0
controller_max_retries: 3
conservative_reset_dist: 2.0
planner_frequency: 5.0
oscillation_timeout: 15.0
oscillation_distance: 0.1
recovery_behavior_enabled: true

recovery_behaviors:

  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

clear_costmap:
    reset_distance: 0.0
    force_updating: true
    affected_maps: both           # Clear obstacles on local_costmap and global_costmap
    layer_names: [obstacle_layer] 

NavfnROS:
  planner_patience: 10.0
  allow_unknown: false
  default_tolerance: 0.0
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: false
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  meter_scoring: true

DWAPlannerROS:
# Robot Configuration Parameters
  max_vel_x:  0.30        # Forward positive
  min_vel_x: -0.30        # Backward negative
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.30
  min_vel_trans: 0.20
  max_vel_theta:  5.0
  min_vel_theta: -5.0
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_theta: 2.0

# Goal Tolerance Parameters
  xy_goal_tolerance:  0.10         # Within 10cm
  yaw_goal_tolerance: 6.2831852    # 2PI radians (360 degrees)
  latch_xy_goal_tolerance: true    # 

# Differential-drive robot configuration
  holonomic_robot: false           # No omni-directional wheels so can't move sideways

# Forward Simulation Parameters
  sim_time: 3.0                    # 4.0 = https://kaiyuzheng.me/documents/papers/ros_navguide.pdf
  vx_samples: 20
  vy_samples: 0
  vth_samples: 60
  controller_frequency: 5.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0            # Default 32, try 60
  goal_distance_bias: 20.0            # Default 24, try 20
  occdist_scale: 0.20                 # "Fear factor" - how careful (slow) to be near obstacles (0.10 is good)
  forward_point_distance: 0.1
  stop_time_buffer: 0.2
  scaling_speed: 0.15
  max_scaling_factor: 0.2
  sim_granularity: 0.025 

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : false
  publish_cost_grid_pc: false
