<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- robot geometric characteristics -->
    <xacro:property name="rvr_body_length" value="0.182"/>
    <xacro:property name="rvr_body_width" value="0.138"/>
    <xacro:property name="rvr_body_height" value="0.043"/>

    <xacro:property name="rvr_wheel_width" value="0.035"/>
    <xacro:property name="rvr_wheel_diameter" value="0.065"/>
    <xacro:property name="rvr_wheel_radius" value="${rvr_wheel_diameter/2}"/>

    <xacro:property name="rvr_track_dz" value="0.0075"/>
    <xacro:property name="rvr_track_length" value="${0.062*2}"/>

</robot>
