<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="track_robot">

    <!--common-->
    <xacro:include filename="$(find sphero_rvr_description)/urdf/common.urdf.xacro" />
    <xacro:include filename="$(find sphero_rvr_description)/urdf/materials.urdf.xacro" />
    <xacro:include filename="$(find sphero_rvr_description)/urdf/geometry.urdf.xacro" />

    <!-- parts -->
    <xacro:include filename="$(find sphero_rvr_description)/urdf/body.urdf.xacro" />
    <xacro:include filename="$(find sphero_rvr_description)/urdf/wheel.urdf.xacro" />

    <!-- urg laser -->
    <xacro:include filename="$(find urg_node)/urdf/hokuyo_ust10.urdf.xacro" />


    <!-- dummy base link no inertia to satisfy kdl -->
    <link name="base_link"/>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${rvr_track_dz - rvr_wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <!-- attach body to base_link -->
    <joint name="body_inertia" type="fixed">
        <parent link="base_link" />
        <child link="body" />
    </joint>

    <!-- body acting as base link inertia -->
    <xacro:body name="body" />

    <!-- tracks -->
    <xacro:wheel name="left_track_back_wheel" parent="base_link" direction="1" >
        <origin xyz="-${rvr_track_length/2} ${rvr_body_width/2} ${rvr_track_dz}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel name="left_track_front_wheel" parent="base_link" direction="1">
        <origin xyz="${rvr_track_length/2} ${rvr_body_width/2} ${rvr_track_dz}" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel name="right_track_back_wheel" parent="base_link" direction="-1" >
        <origin xyz="-${rvr_track_length/2} -${rvr_body_width/2} ${rvr_track_dz}" rpy="${M_PI} 0 0" />
    </xacro:wheel>
    <xacro:wheel name="right_track_front_wheel" parent="base_link" direction="-1">
        <origin xyz="${rvr_track_length/2} -${rvr_body_width/2} ${rvr_track_dz}" rpy="${M_PI} 0 0" />
    </xacro:wheel>

    <!-- laser -->
    <xacro:hokuyo_ust10_mount parent_link="base_link" prefix="urg" topic="scan" >
        <origin xyz="${-0.03} 0 ${rvr_body_height + 0.035}" rpy="0 0 0" />
    </xacro:hokuyo_ust10_mount>

    <!-- gazebo extras -->
    <!-- gazebo control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

    <!-- imu -->
    <gazebo>
        <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
            <robotNamespace>/</robotNamespace>
            <alwaysOn>true</alwaysOn>
            <updateRate>10.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>rvr_driver/imu/data</topicName>
            <accelDrift>0.001 0.001 0.001</accelDrift>
            <accelGaussianNoise>0.001 0.001 0.001</accelGaussianNoise>
            <rateDrift>0.001 0.001 0.001</rateDrift>
            <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
            <headingDrift>0.001</headingDrift>
            <headingGaussianNoise>0.005</headingGaussianNoise>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
    </gazebo>
</robot>
