<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="wheel" params="name parent direction:=1 *origin">

        <xacro:include filename="$(find sphero_rvr_description)/urdf/geometry.urdf.xacro" />

        <joint name="${name}_joint" type="continuous" >
            <parent link="${parent}" />
            <child link="${name}" />
            <xacro:insert_block name="origin" />
            <axis xyz="0 ${direction} 0" rpy="0 0 0" />
            <limit effort="10.0" velocity="50.0" />
        </joint>

        <link name="${name}">
            <visual>
                <origin xyz="0 ${rvr_wheel_width/2} 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${rvr_wheel_radius}" length="${rvr_wheel_width}" />
                </geometry>
                <material name="DarkGrey"/>
            </visual>
            <collision >
                <origin xyz="0 ${rvr_wheel_width/2} 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${1.05*rvr_wheel_radius}" length="${1.05*rvr_wheel_width}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.076" />
                <inertia
                    ixx="${0.001}" ixy="0.0" ixz="0.0"
                    iyy="${0.001}" iyz="0.0"
                    izz="${0.001}"/>
            </inertial>
        </link>

        <joint name="${name}_taco_joint" type="fixed">
            <parent link="${name}" />
            <child link="${name}_taco" />
            <origin xyz="0 ${rvr_wheel_width / 2} ${1.05*rvr_wheel_radius}" rpy="0 0 0" />
        </joint>

        <link name="${name}_taco">
            <visual>
                <geometry>
                    <cylinder radius="0.005" length="0.004" />
                </geometry>
                <material name="Red"/>
            </visual>
        </link>

        <gazebo reference="${name}">
			<mu1 value="0.8"/>
			<mu2 value="0.8"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
		</gazebo>

        <transmission name="${name}_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${name}_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${name}_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>

</robot>
