footprint: [[-0.09, -0.09], [-0.09, 0.09], [0.09, 0.09], [0.09, -0.09]]
footprint_padding: 0.02

robot_base_frame: base_footprint
# update_frequency: 10.0
update_frequency: 5.0
# publish_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 7.5
raytrace_range: 8.0

# layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.01
